version: '3.8'
services:
  yolo_fine_tunning:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/opt/project/
    runtime: nvidia
    shm_size: "16gb"
    ports:
      - 5151:5151
    environment:
      - LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH
